### ISSUE TITLE
Week 2 Assignment Quickstart

### ISSUE THREAD

**Issue by elam3** [elam3/Flicks#1]
/cc @CCSF-Coders/TAs-iOS

I made a new branch called wk02_quickstarts, with one new commit that encompasses:
* Assignment Quickstart - Navigation and Passing Data
* Assignment Quickstart - Safely Getting Images

https://github.com/elam3/Flicks/commit/c04502f323266c83ff6c7a4524f9e4eedadabab1

**Comment by codepathreview** [comment]
👍 Nice work! The point of this homework was to get a chance to implement a TableView (one of the most common views in iOS) and to work with real data over the network (in this case from the Movies Database API).

A key part of these projects is that you add additional features and tweak the UI / UX because that will provide the most learning opportunities. We encourage you to complete the projects early each week with the required stories and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

We have a detailed [Assignment 1 Feedback Guide](https://courses.codepath.com/snippets/ios_university/feedback_guides/project_1_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at <universitysupport@codepath.com>.

**Comment by kmolo** [comment]
nice @elam3, just add the Week 2 README as well:
https://courses.codepath.com/snippets/ios_university/readme_templates/assignment_2_readme.md?raw=true
